[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
runOnSave = true

[theme]
primaryColor = "#F39C12"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#000000"
font = "sans serif"

[global]
# Set the default page title
pageTitle = "Honeydew Agent"
